[package]
name = "silver-chainsaw"
version = "0.1.0"
authors = ["Frederik Braun <fbraun@mozilla.com>"]

[dependencies]
getopts = "0.2"
regex = "1.0.5"
serde = "1.0.80"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7.1"